### ISSUE TITLE
Add ability to sign up via Google

### ISSUE THREAD

**Issue by hcarnes** [hcarnes/theodora#12]
Now that login is available via Google, users should be able to sign up with Google instead of having to have an existing account

**Comment by CoderJolly** [comment]
pls assign this issue to me

**Comment by CoderJolly** [comment]
I will do it via Omniauth

**Comment by hcarnes** [comment]
Unfortunately I can only assign to folks with push access on Github, would like to see a pull request for this issue though! We are already using omniauth, the functionality just needs to be built out. One of the things to consider is that we do need to add the ability for users to create organizations, possibly on signup. That might be worth taking a stab at first before this one, as however that ends up working will affect this. Check out #14

**Comment by hcarnes** [comment]
Currently users can only sign in to existing accounts with Google, they can't yet sign up with Google, hence the name of this ticket.
