### ISSUE TITLE
Creation of new organization

### ISSUE THREAD

**Issue by hcarnes** [hcarnes/theodora#14]
If the user signing up is a totally new organization, they should be allowed to create a new organization from scratch.

**Comment by JoyBhalla** [comment]
Can I work on this ?

**Comment by hcarnes** [comment]
Hi! Thanks for your interest. Yes, you can work on this. Let me know if you
have any questions. You can submit a pull request when you are done and I
will review. Thanks!

**Comment by JoyBhalla** [comment]
Okay,will do !

**Comment by JoyBhalla** [comment]
I will not be able to work on this for now,if anyone wants to take this up please do.

**Comment by hcarnes** [comment]
Okay, I will work on this issue. Thanks for your interest!
